import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar";
import Script from "next/script";
import "./globals.css";

export const metadata: Metadata = {
  title: "lim_test_next_project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div style={{ display: 'flex', minHeight: '100vh' }}>
          <Sidebar />
          <main style={{ flexGrow: 1, padding: '20px', overflowY: 'auto' }}>
            {children}
          </main>
        </div>
        <Script src="https://www.eformsign.com/lib/js/efs_embedded_v2.js" strategy="beforeInteractive" />
      </body>
    </html>
  );
}
